In [36]:
from datascience import*
import numpy as np

import warnings
warnings.simplefilter(action='ignore', category=np.VisibleDeprecationWarning)

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')


In [3]:
pets = make_array('cat', 'cat', 'dog', 'cat', 'dog', 'rabbit')

In [4]:
pets

array(['cat', 'cat', 'dog', 'cat', 'dog', 'rabbit'], dtype='<U6')

In [5]:
pets == 'cat'

array([ True,  True, False,  True, False, False])

In [7]:
sum(pets == 'cat')

3

In [ ]:
#Same job, different way of writing

In [8]:
np.count_nonzero(pets == 'dog')

2

In [9]:
x = np.arange(20, 31)

In [10]:
x

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [11]:
x > 28

array([False, False, False, False, False, False, False, False, False,
        True,  True])

In [15]:
#Operations possible with an array not a list

In [17]:
x = [20, 21, 22, 23, 24]

In [18]:
#Doesn't work
x>21

TypeError: '>' not supported between instances of 'list' and 'int'

In [19]:
#Doesn't work
x+1

TypeError: can only concatenate list (not "int") to list

## Random Selection

## Simulation

In [56]:
#np.random.choice
#Find a way to simulate two dice rolls
#Compute how much money we win/lose based on the result
#Do steps 1 and 2 10,000 times

In [91]:
#Append an array
#np.append(array_1, value)
#np.append(array_1, array_2)

In [59]:
#With Replacement (can get the same twice)
#Selects uniformly at random
#From an array
#a specified number of times

In [60]:
#np.random.choce(some_array, sample_size)

In [63]:
mornings = make_array('wake up', 'sleep in')

In [66]:
np.random.choice(mornings)

'wake up'

In [65]:
np.random.choice(mornings)

'sleep in'

### We can also pass an argument that specifies how many times to make a random choice

In [68]:
np.random.choice(mornings, 7)

array(['sleep in', 'wake up', 'wake up', 'wake up', 'wake up', 'wake up',
       'wake up'], dtype='<U8')

In [74]:
sum(np.random.choice(mornings, 7)== 'wake up')

5

In [77]:
plan = np.random.choice(mornings, 7)
plan

array(['wake up', 'sleep in', 'sleep in', 'sleep in', 'sleep in',
       'wake up', 'sleep in'], dtype='<U8')

In [78]:
sum(plan == 'wake up')

2

In [79]:
sum(plan == 'sleep in')

5

## Simulating the roll of a die

In [80]:
die_faces = np.arange(1,7) #Not including 7

In [81]:
np.random.choice(die_faces)

5

In [83]:
def simulate_one_round():
    my_roll = np.random.choice(die_faces)
    your_roll = np.random.choice(die_faces)
    return one_round(my_roll, your_roll)

In [90]:
simulate_one_round()

-1

In [89]:
simulate_one_round()

-1

In [92]:
first = np.arange(4)
second = np.arange(10,7)

In [93]:
np.append(first, second)

array([0, 1, 2, 3])

In [94]:
np.append(first, 6)

array([0, 1, 2, 3, 6])

## Loops